server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.qr.default-expiration-minutes=10
app.base-url=http://localhost:3000
app.cors.allowed-origins=http://localhost:3000,http://localhost:8090,http://localhost:8080

logging.level.com.attendance=DEBUG
